services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
    networks:
      - ksk_network

  database:
    image: mariadb:${MYSQL_VERSION:-lts}
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-app}
      MYSQL_TCP_PORT: 3306
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - ksk_network

volumes:
  redis_data:
  database_data:

networks:
  ksk_network:
    driver: bridge
