services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./storage:/app/storage
      - ./bootstrap/cache:/app/bootstrap/cache
      - .:/app
      - /app/node_modules
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    networks:
      - ksk_network

  ###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:${MYSQL_VERSION:-lts}
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-app}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 3
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - ksk_network

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minio}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minio123}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data
    networks:
      - ksk_network

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - ksk_network

volumes:
  caddy_data:
  caddy_config:

  minio_data:
  redis_data:
  database_data:

networks:
  ksk_network:
    driver: bridge
